name: Daily Report

on:
  schedule:
    - cron: '0 4 * * *'  # 北京时间中午12:00 (UTC+8)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          cat <<'EOF' > .env
          REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT=${{ secrets.REDDIT_USER_AGENT }}
          LLM_API_KEY=${{ secrets.LLM_API_KEY }}
          LLM_MODEL=${{ secrets.LLM_MODEL }}
          LLM_BASE_URL=${{ secrets.LLM_BASE_URL }}
          LLM_TEMPERATURE=${{ secrets.LLM_TEMPERATURE }}
          LLM_MAX_TOKENS=${{ secrets.LLM_MAX_TOKENS }}
          EOF

      - name: Generate daily report
        run: python main.py

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push reports
        run: |
          git add reports
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily report $(date +'%Y-%m-%d') [skip ci]"
            git push
          fi
